# Generated by Django 3.1.1 on 2020-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='line_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='line_text',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
