# Generated by Django 3.1.1 on 2020-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_auto_20200912_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='line_pts',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='line_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
