# Generated by Django 3.1.1 on 2020-09-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_auto_20200912_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selections',
            new_name='Bets',
        ),
    ]
