# Generated by Django 3.1.1 on 2020-09-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0005_auto_20200912_1644"),
    ]

    operations = [
        migrations.RenameModel(old_name="Bets", new_name="Bet",),
    ]
